print ('\033[1;36m'+"╔══════════════════════════════════════════════════════╗")
print ('\033[1;36m'+"║                  PROYECTO FINAL                      ║")
print ('\033[1;36m'+"║══════════════════════════════════════════════════════║")
print ('\033[1;36m'+"║MENU DE APLICACIONES                                  ║")
print ('\033[1;36m'+"║1.DISCORD                                             ║")
print ('\033[1;36m'+"║2.CALENDARIO                                          ║")
print ('\033[1;36m'+"║3.CALCULADORA                                         ║")
print ('\033[1;36m'+"║4.TELEFONO                                            ║")
print ('\033[1;36m'+"║0.SALIR DEL MENU                                      ║")
print ('\033[1;36m'+"╚══════════════════════════════════════════════════════╝")
apli=input("SELECCIONA UNA APLICACION-->")
